### ISSUE TITLE
on Windows 10：ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ouuan** [rikakomoe/copywriting-correct#3]
我在使用 [remark-lint](https://github.com/remarkjs/remark-lint) with remark-copywriting-correct 时，报错如下：

```
<stdin>
  1:1  error  Error: Cannot parse file `.remarkrc`
Cannot parse script `C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-copywriting-correct\index.js`
ReferenceError: window is not defined
    at Object.<anonymous> (C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-copywriting-correct\node_modules\copywriting-correct\dist\copywriting-correct.common.js:574:4)
    at __webpack_require__ (C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-copywriting-correct\node_modules\copywriting-correct\dist\copywriting-correct.common.js:39:30)
    at Object.<anonymous> (C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-copywriting-correct\node_modules\copywriting-correct\dist\copywriting-correct.common.js:469:13)
    at __webpack_require__ (C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-copywriting-correct\node_modules\copywriting-correct\dist\copywriting-correct.common.js:39:30)
    at Object.<anonymous> (C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-copywriting-correct\node_modules\copywriting-correct\dist\copywriting-correct.common.js:523:24)
    at __webpack_require__ (C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-copywriting-correct\node_modules\copywriting-correct\dist\copywriting-correct.common.js:39:30)
    at Object.<anonymous> (C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-copywriting-correct\node_modules\copywriting-correct\dist\copywriting-correct.common.js:1535:35)
    at __webpack_require__ (C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-copywriting-correct\node_modules\copywriting-correct\dist\copywriting-correct.common.js:39:30)
    at C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-copywriting-correct\node_modules\copywriting-correct\dist\copywriting-correct.common.js:103:18
    at C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-copywriting-correct\node_modules\copywriting-correct\dist\copywriting-correct.common.js:106:10
    at Error (C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-cli\node_modules\fault\index.js:29:12)
    at done (C:\Users\yyfouuan\AppData\Roaming\npm\node_modules\remark-cli\node_modules\unified-engine\lib\find-up.js:156:11)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

× 1 error
```

环境：

- Windows 10 家庭中文版 1903
- Node 12.13.1

解决方案：

将 https://github.com/rikakomoe/copywriting-correct/commit/a6d64ed7bfbe119332d57e2e83998cd18fe9ebda#diff-e947c22935dcd695a75b4721c182e795R574 中的 `window` 改为 `this`，未报错，未发现异常。

**Comment by satouriko** [comment]
试下 1.0.7
